name: first shot

on: push

jobs:
  my-job:
    name: My Job runs on python ${{ matrix.python_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          python_version: [3.7]
          os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
        with:
          ref: release
      - name: test with python ${{ matrix.python_version }}
        # This step checks out a copy of your repository.
        #- uses: actions/checkout@v1
        # This step references the directory that contains the action.
        #- uses: ./.github/actions/tests
        run: |
          ls -la
          python3 --version
          pip --version
          pip3 --version
          echo "pip install -U pip"
          pip install -U pip          
          echo "pip3 install -U pip3"
          pip3 install -U pip3
          pip3 install -r requirements.txt
          cd hadoop_yarn_cluster_checker_model
          python3 test.py
          python3 -m pytest test --junitxml=./test-reports/coverage.xml
      - name: build
        run: |
            pip3 freeze > requirements.txt
            python3 setup.py sdist bdist_wheel



